version: '3.8'
services:

  backend:
    build: ./backend
    expose:
      - 8000
    command: gunicorn guesstop.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - ./backend/.env.prod
    depends_on:
      - db
    environment:
      - DB_HOST=db
    volumes:
      - static_volume:/backend/static
    restart: unless-stopped

  bot:
    build: ./bot
    volumes:
      - ./bot:/bot
    depends_on:
      - backend
      - redis
    command: python bot.py
    environment:
      - BACKEND_HOST=backend
      - REDIS_HOST=redis
    restart: unless-stopped

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/.env.db
    restart: unless-stopped

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    restart: unless-stopped

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - backend
    volumes:
      - static_volume:/backend/static

volumes:
  postgres_data:
  static_volume:
