# Generated by Django 4.2 on 2023-04-08 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('matches', models.TextField(verbose_name='Шаблон совпадений')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.PositiveIntegerField(verbose_name='Telegram ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('score', models.PositiveSmallIntegerField(verbose_name='Очки')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('complexity', models.FloatField(verbose_name='Сложность')),
            ],
        ),
        migrations.CreateModel(
            name='TopicEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special_matches', models.TextField(verbose_name='Шаблон совпадений')),
                ('position', models.PositiveSmallIntegerField(verbose_name='Место')),
                ('answers_count', models.PositiveIntegerField(verbose_name='Количество ответов')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.entity')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.topic')),
            ],
        ),
        migrations.AddField(
            model_name='entity',
            name='topics',
            field=models.ManyToManyField(related_name='entities', through='game.TopicEntity', to='game.topic'),
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(verbose_name='Очки')),
                ('started_at', models.DateTimeField(verbose_name='Начало')),
                ('finished_at', models.DateTimeField(verbose_name='Окончание')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='game.player')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='game.topic')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Ответ')),
                ('position', models.PositiveSmallIntegerField(verbose_name='Место')),
                ('sent_at', models.DateTimeField(verbose_name='Отправлен')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='game.attempt')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='game.topicentity')),
            ],
        ),
    ]
