# Generated by Django 4.2 on 2023-04-10 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(verbose_name='Очки')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начало')),
                ('finished_at', models.DateTimeField(verbose_name='Окончание')),
            ],
        ),
        migrations.RemoveField(
            model_name='answer',
            name='attempt',
        ),
        migrations.RemoveField(
            model_name='topicentity',
            name='special_matches',
        ),
        migrations.AddField(
            model_name='entity',
            name='pattern',
            field=models.CharField(default=1, max_length=100, verbose_name='Паттерн'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='level',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Уровень'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='excluded_words',
            field=models.CharField(default=1, max_length=100, verbose_name='Список исключаемых слов'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='hint',
            field=models.TextField(default=1, verbose_name='Подсказка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='game.topicentity'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='matches',
            field=models.TextField(verbose_name='Список совпадений'),
        ),
        migrations.DeleteModel(
            name='Attempt',
        ),
        migrations.AddField(
            model_name='round',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rounds', to='game.player'),
        ),
        migrations.AddField(
            model_name='round',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rounds', to='game.topic'),
        ),
        migrations.AddField(
            model_name='answer',
            name='round',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='game.round'),
            preserve_default=False,
        ),
    ]
