# Generated by Django 4.2 on 2023-04-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_round_remove_answer_attempt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='excluded_words',
        ),
        migrations.AddField(
            model_name='topic',
            name='exclusions',
            field=models.CharField(default='', max_length=100, verbose_name='Исключаемые слова'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topicentity',
            name='initial_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Изначальное количество ответов'),
            preserve_default=False,
        ),
    ]
