# Generated by Django 4.2 on 2023-04-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_topic_matches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Отправлен'),
        ),
    ]
