# Generated by Django 4.2 on 2023-04-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_answer_position_alter_answer_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='score',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Очки'),
        ),
        migrations.AlterField(
            model_name='round',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Окончание'),
        ),
        migrations.AlterField(
            model_name='round',
            name='score',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Очки'),
        ),
    ]
