# Generated by Django 4.2 on 2023-04-12 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_alter_player_score_alter_round_finished_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='telegram_id',
            field=models.PositiveIntegerField(unique=True, verbose_name='Telegram ID'),
        ),
        migrations.AlterUniqueTogether(
            name='round',
            unique_together={('player', 'topic')},
        ),
    ]
