# Generated by Django 4.2 on 2023-04-12 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_alter_player_telegram_id_alter_round_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='entity',
            new_name='topic_entity',
        ),
    ]
