# Generated by Django 4.2 on 2023-04-13 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_rename_entity_answer_topic_entity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='complexity',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='level',
        ),
        migrations.AddField(
            model_name='topic',
            name='average_score',
            field=models.FloatField(default=0, verbose_name='Средний результат'),
        ),
        migrations.AddField(
            model_name='topic',
            name='updated',
            field=models.BooleanField(default=True, verbose_name='Статистика обновлена'),
        ),
    ]
