# Generated by Django 4.2 on 2023-04-13 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_remove_topic_complexity_remove_topic_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='updated',
        ),
    ]
