# Generated by Django 4.2 on 2023-04-17 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_player_referrer_alter_answer_round_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='telegram_username',
            field=models.CharField(default='username', max_length=100, verbose_name='Telegram Username'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='referrer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='game.player', verbose_name='Реферер'),
        ),
    ]
