# Generated by Django 4.2 on 2023-04-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_player_telegram_username_alter_player_referrer'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='bot_answers',
            field=models.TextField(default='', verbose_name='Список ответов бота'),
            preserve_default=False,
        ),
    ]
