# Generated by Django 4.2 on 2023-04-18 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_topic_bot_answers'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='round',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='player',
            name='score',
        ),
        migrations.AddField(
            model_name='answer',
            name='player',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2)], default=1, verbose_name='Игрок'),
        ),
        migrations.AddField(
            model_name='player',
            name='average_score',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Среднее число очков'),
        ),
        migrations.AddField(
            model_name='player',
            name='defeats',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Число поражений'),
        ),
        migrations.AddField(
            model_name='player',
            name='draws',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Число ничьих'),
        ),
        migrations.AddField(
            model_name='player',
            name='duel_average_score',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Среднее число очков в дуэлях'),
        ),
        migrations.AddField(
            model_name='player',
            name='duel_defeats',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Число поражений в дуэлях'),
        ),
        migrations.AddField(
            model_name='player',
            name='duel_draws',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Число ничьих в дуэлях'),
        ),
        migrations.AddField(
            model_name='player',
            name='duel_rating',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Рейтинг в дуэлях'),
        ),
        migrations.AddField(
            model_name='player',
            name='duel_victories',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Число побед в дуэлях'),
        ),
        migrations.AddField(
            model_name='player',
            name='victories',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Число побед'),
        ),
        migrations.AddField(
            model_name='round',
            name='duel',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Дуэль'),
        ),
        migrations.AddField(
            model_name='round',
            name='player1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='rounds', to='game.player', verbose_name='Игрок 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='round',
            name='player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guest_rounds', to='game.player', verbose_name='Игрок 2'),
        ),
        migrations.AddField(
            model_name='round',
            name='score1',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Очки первого игрока'),
        ),
        migrations.AddField(
            model_name='round',
            name='score2',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Очки второго игрока'),
        ),
        migrations.AlterUniqueTogether(
            name='round',
            unique_together={('player1', 'player2', 'topic')},
        ),
        migrations.RemoveField(
            model_name='round',
            name='player',
        ),
        migrations.RemoveField(
            model_name='round',
            name='score',
        ),
    ]
