# Generated by Django 4.2 on 2023-05-09 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_alter_round_unique_together_remove_player_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='bot_answers',
            field=models.TextField(default='{}', verbose_name='Список ответов бота'),
        ),
    ]
