# Generated by Django 4.2 on 2023-05-09 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_alter_topic_bot_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='bot_answers',
            field=models.TextField(default='{}', verbose_name='Список возможных ответов бота'),
        ),
    ]
