# Generated by Django 4.2 on 2023-05-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_alter_topicentity_options_round_player1_feedback_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='topicentity',
            name='position',
            field=models.PositiveSmallIntegerField(db_index=True, verbose_name='Место'),
        ),
    ]
