# Generated by Django 4.2 on 2023-05-12 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_alter_entity_options_alter_entity_matches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicentity',
            name='answers_count',
            field=models.PositiveIntegerField(blank=True, verbose_name='Количество ответов'),
        ),
        migrations.AlterField(
            model_name='topicentity',
            name='initial_count',
            field=models.PositiveIntegerField(blank=True, verbose_name='Изначальное количество ответов'),
        ),
        migrations.AlterField(
            model_name='topicentity',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, verbose_name='Место'),
        ),
    ]
