# Generated by Django 4.2 on 2023-05-12 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0024_alter_topicentity_answers_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='exclusions',
            field=models.CharField(blank=True, max_length=100, verbose_name='Исключаемые слова'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='hint',
            field=models.TextField(blank=True, verbose_name='Подсказка'),
        ),
    ]
