# Generated by Django 4.2 on 2023-05-20 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0025_alter_topic_exclusions_alter_topic_hint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'ordering': ['title'], 'verbose_name_plural': 'entities'},
        ),
        migrations.AlterModelOptions(
            name='round',
            options={'ordering': ['-started_at']},
        ),
        migrations.AlterModelOptions(
            name='topicentity',
            options={'ordering': ['position'], 'verbose_name_plural': 'topic entities'},
        ),
        migrations.AddField(
            model_name='player',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Рейтинг против бота'),
        ),
        migrations.AlterField(
            model_name='topicentity',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_entities', to='game.topic', verbose_name='Тема'),
        ),
    ]
