# Generated by Django 4.2 on 2023-05-24 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0026_alter_entity_options_alter_round_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='topicentity',
            unique_together={('topic', 'entity')},
        ),
    ]
