# Generated by Django 4.2 on 2023-06-08 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0028_round_hits1_round_hits2_round_hits_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='discarded',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Отклонён'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='round',
            name='hits_mode',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Режим хитов'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='average_score_hits_mode',
            field=models.FloatField(default=0, verbose_name='Средний результат в хитах'),
        ),
    ]
