# Generated by Django 4.2 on 2023-06-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0030_alter_answer_discarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='checked',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Проверен'),
        ),
    ]
