# Generated by Django 4.2 on 2023-06-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0031_round_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='declined_answers',
            field=models.TextField(default='[]', verbose_name='Отклонённые ответы'),
        ),
    ]
