# Generated by Django 4.2 on 2023-06-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0032_round_declined_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='best_rating',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Наилучший обычный рейтинг'),
        ),
        migrations.AddField(
            model_name='player',
            name='best_rating_reached_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Наилучший обычный рейтинг установлен'),
        ),
        migrations.AlterField(
            model_name='player',
            name='duel_rating',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Дуэльный рейтинг'),
        ),
        migrations.AlterField(
            model_name='player',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Обычный рейтинг'),
        ),
    ]
