# Generated by Django 4.2 on 2023-06-26 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0033_player_best_rating_player_best_rating_reached_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='round',
            old_name='player1_feedback',
            new_name='feedback1',
        ),
        migrations.RenameField(
            model_name='round',
            old_name='player2_feedback',
            new_name='feedback2',
        ),
    ]
