# Generated by Django 4.2 on 2023-07-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0034_rename_player1_feedback_round_feedback1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='telegram_id',
            field=models.PositiveBigIntegerField(unique=True, verbose_name='Telegram ID'),
        ),
    ]
